### ISSUE TITLE
model search is broken

### ISSUE THREAD

**Issue by ralyodio** [nat/openplayground#57]
```
$ openplayground run
INFO:server.lib.sseserver:SUBSCRIBING TO: inferences
INFO:server.lib.sseserver:SUBSCRIBING TO: notifications
INFO:server.lib.sseserver:GETTING TOPIC: notifications
INFO:server.lib.sseserver:GETTING TOPIC: inferences
INFO:server.app:Initializing download manager...
INFO:server.app:Download loop started...
 * Serving Flask app 'server.app'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:5432
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:20] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:20] "GET /index.d826928d.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:20] "GET /index.e96bf64d.css HTTP/1.1" 200 -
INFO:server.lib.api:Getting enabled models
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:20] "GET /api/models-enabled HTTP/1.1" 200 -
INFO:server.lib.api:Received notification request
INFO:server.lib.sseserver:LISTENING TO: notifications
INFO:server.lib.sseserver:LISTENING
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:20] "GET /favicon.ico HTTP/1.1" 200 -
INFO:server.lib.api:Getting enabled models
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:23] "GET /api/models-enabled HTTP/1.1" 200 -
INFO:server.lib.api:Getting enabled models
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:29] "GET /api/models-enabled HTTP/1.1" 200 -
INFO:server.lib.api:Getting providers with models
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:36] "GET /api/providers-with-key-and-models HTTP/1.1" 200 -
INFO:server.lib.api.provider:Searching Provider Models openplayground
ERROR:server.app:Exception on /api/provider/openplayground/models/search [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fee4b826bc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openplayground.filler', port=443): Max retries exceeded with url: /api/search?q=gpt4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee4b826bc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ettinger/.local/lib/python3.10/site-packages/server/lib/api/provider.py", line 111, in provider_models_search
    response = requests.get(search_url)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openplayground.filler', port=443): Max retries exceeded with url: /api/search?q=gpt4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee4b826bc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:02:57] "GET /api/provider/openplayground/models/search?query=gpt4 HTTP/1.1" 500 -
INFO:server.lib.api.provider:Searching Provider Models openplayground
ERROR:server.app:Exception on /api/provider/openplayground/models/search [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fee4b824610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openplayground.filler', port=443): Max retries exceeded with url: /api/search?q=gpt4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee4b824610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ettinger/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ettinger/.local/lib/python3.10/site-packages/server/lib/api/provider.py", line 111, in provider_models_search
    response = requests.get(search_url)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openplayground.filler', port=443): Max retries exceeded with url: /api/search?q=gpt4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee4b824610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:03:00] "GET /api/provider/openplayground/models/search?query=gpt4 HTTP/1.1" 500 -
INFO:server.lib.api:Getting enabled models
INFO:werkzeug:127.0.0.1 - - [23/Apr/2023 00:03:11] "GET /api/models-enabled HTTP/1.1" 200 -
INFO:server.lib.api:Getting enabled models
```

**Comment by ralyodio** [comment]
I had to add huggingface api key
