### ISSUE TITLE
add upload for models

### ISSUE THREAD

**Issue by iHaagcom** [nat/openplayground#8]
Can you please provide an example of how to load a .bin model please?

**Comment by iHaagcom** [comment]
Even .pt models, there isn't much instruction for these either.

**Comment by iHaagcom** [comment]
Just tried openplayground run -m "e:\Machine Learning\ggml-alpaca-7b-native-q4.bin"

Machine Learning\gpt4all-lora-quantized.bin"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError

**Comment by AlexanderLourenco** [comment]
We will add examples in the next couple of days :)
Unfortunately, you won't be able to load .pt files directly. Instead, you'd have to create a WebSocket server wrapper so that the UI can communicate with external models

**Comment by iHaagcom** [comment]
> We will add examples in the next couple of days :)
> 
> Unfortunately, you won't be able to load .pt files directly. Instead, you'd have to create a WebSocket server wrapper so that the UI can communicate with external models

What about .bin models?

**Comment by mmyjona** [comment]
> > We will add examples in the next couple of days :)
> > 
> > Unfortunately, you won't be able to load .pt files directly. Instead, you'd have to create a WebSocket server wrapper so that the UI can communicate with external models
> 
> What about .bin models?

check my pr

**Comment by AB0x** [comment]
> check my pr

What do you mean by that?

**Comment by iHaagcom** [comment]
Awesome looking forward to it.
